Tendrl/monitoring-integration

LICENSE
MANIFEST.in
Makefile
setup.py
tendrl-monitoring-integration.spec

Add entry point to execute tendrl-monitoring-integration

Packaging: Build script for tendrl-monitoring-integration

---

tendrl-monitoring-integration.spec

add buildrequires python-setuptools

Packaging: fix copr build issue

---

tendrl/monitoring_integration/grafana/cluster_detail.py
tendrl/monitoring_integration/grafana/cluster_details.py
tendrl/monitoring_integration/grafana/create_alert_dashboard.py
tendrl/monitoring_integration/grafana/create_dashboards.py
tendrl/monitoring_integration/grafana/create_new_notification_channel.py
tendrl/monitoring_integration/grafana/webhook_receiver.py
tendrl/monitoring_integration/manager/__init__.py
tendrl/monitoring_integration/sync/__init__.py

Functionality to create alert dashboards and webhook-receiver

---

etc/tendrl/monitoring-integration/monitoring-integration.conf.yaml.sample
tendrl/monitoring_integration/flows/update_dashboard/__init__.py
tendrl/monitoring_integration/flows/update_dashboard/alert_utils.py
tendrl/monitoring_integration/grafana/cluster_detail.py
tendrl/monitoring_integration/grafana/create_dashboards.py
tendrl/monitoring_integration/grafana/utils.py
tendrl/monitoring_integration/graphite/__init__.py
tendrl/monitoring_integration/graphite/graphite_utils.py
tendrl/monitoring_integration/manager/__init__.py
tendrl/monitoring_integration/objects/definition/monitoring_integration.yaml
tendrl/monitoring_integration/objects/trigger/__init__.py
tendrl/monitoring_integration/sync/__init__.py

tendrl-bug-id: Tendrl/monitoring-integration#32

Functionality to insert aggregated data into graphite.

---

tendrl/monitoring_integration/manager/__init__.py

tendrl-bug-id: Tendrl/monitoring-integration#39

Updating log messages

---

etc/tendrl/monitoring-integration/grafana/dashboards/tendrl-gluster-volumes.json

Signed-off-by: anmolbabu <anmolbudugutta@gmail.com>

Fix brick count at volume dashboard

---

etc/tendrl/monitoring-integration/grafana/dashboards/tendrl-gluster-at-a-glance.json

tendrl-bug-id: https://github.com/Tendrl/monitoring-integration/issues/44

Top 5 bricks by utilization fails if all bricks have same name

---

tendrl/monitoring_integration/grafana/webhook_receiver.py
tendrl/monitoring_integration/manager/__init__.py

Modified webhook receiver as class and added exception handling

---

etc/tendrl/monitoring-integration/monitoring-integration.conf.yaml.sample
tendrl/monitoring_integration/manager/__init__.py

tendrl-bug-id: Tendrl/monitoring-integration#68

Enabling internal profiling

---

tendrl-monitoring-integration.service

tendrl-bug-id: Tendrl/monitoring-integration#61

Adding grafana dependency to .service file

---

tendrl/monitoring_integration/alert/utils.py

tendrl-bug-id: Tendrl/monitoring-integration#75

Small fix in alerting utils

---

etc/grafana/grafana.ini
tendrl/monitoring_integration/grafana/create_alert_dashboard.py
tendrl/monitoring_integration/grafana/dashboard.py
tendrl/monitoring_integration/grafana/grafana_org_utils.py

tendrl-bug-id: Tendrl/monitoring-integration#71

Add functionality to create new organisation

---

tendrl-monitoring-integration.spec

tendrl-bug-id: Tendrl/monitoring-integration#60

Updating spec file as per https://github.com/Tendrl/tendrl-ansible/issues/29

---

tendrl/monitoring_integration/grafana/cluster_detail.py
tendrl/monitoring_integration/graphite/__init__.py
tendrl/monitoring_integration/graphite/graphite_utils.py
tendrl/monitoring_integration/objects/definition/monitoring_integration.yaml

tendrl-bug-id: Tendrl/monitoring-integration#60

Updating functionality of adding aggregated data to graphite

---

etc/grafana/grafana.ini
tendrl-monitoring-integration.spec

tendrl-bug-id:Tendrl/monitoring-integration#62

Grafana user management

---

tendrl-monitoring-integration.service

tendrl-bug-id: Tendrl/monitoring-integration#61

Adding grafana dependency to monitoring-integration

---

tendrl/monitoring_integration/grafana/create_dashboards.py

tendrl-bug-id: Tendrl/monitoring-integration#66

Updating alert data

---

tendrl/monitoring_integration/alert/handlers/node/capacity_utilization_handler.py

tendrl-bug-id: Tendrl/monitoring-integration#88

Added handler for capacity utilization trend in node level

---

etc/tendrl/monitoring-integration/grafana/dashboards/tendrl-gluster-at-a-glance.json
etc/tendrl/monitoring-integration/grafana/dashboards/tendrl-gluster-bricks.json
etc/tendrl/monitoring-integration/grafana/dashboards/tendrl-gluster-hosts.json
etc/tendrl/monitoring-integration/grafana/dashboards/tendrl-gluster-volumes.json

#tendrl-bug-id:  https://github.com/Tendrl/monitoring-integration/issues/92

New dashboard added for milestone 3

---

tendrl/monitoring_integration/flows/update_dashboard/__init__.py
tendrl/monitoring_integration/flows/update_dashboard/alert_utils.py
tendrl/monitoring_integration/grafana/create_dashboards.py

tendrl-bug-id: Tendrl/monitoring-integration#93

Updating functionality to upload alert dashboard functionality

---

Makefile
tendrl-monitoring-integration.spec

Files will be installed in
/var/lib/grafana/plugins/Vonage-Grafana_Status_panel directory

Install vonage-panel for grafana

---

tendrl/monitoring_integration/flows/create_alert_dashboard/__init__.py
tendrl/monitoring_integration/flows/new_cluster_dashboard/__init__.py
tendrl/monitoring_integration/flows/update_dashboard/__init__.py
tendrl/monitoring_integration/grafana/create_alert_dashboard.py
tendrl/monitoring_integration/grafana/create_dashboards.py
tendrl/monitoring_integration/objects/definition/monitoring_integration.yaml

tendrl-bug-id: Tendrl/monitoring-integration#105

Adding functionality to create new flow to update alert dashboard

---

tendrl/monitoring_integration/alert/handlers/__init__.py
tendrl/monitoring_integration/alert/handlers/cluster/gluster/brick_utilization_handler.py
tendrl/monitoring_integration/alert/handlers/cluster/gluster/cluster_utilization_handler.py
tendrl/monitoring_integration/alert/handlers/cluster/gluster/volume_utilization_handler.py

Replaced cluster name using integration id in alert messages

---

tendrl/monitoring_integration/flows/update_dashboard/__init__.py

Corrected the updating of bricks alert dashboard as part of volume

---

etc/tendrl/monitoring-integration/grafana/dashboards/tendrl-gluster-at-a-glance.json
etc/tendrl/monitoring-integration/grafana/dashboards/tendrl-gluster-hosts.json
etc/tendrl/monitoring-integration/grafana/dashboards/tendrl-gluster-volumes.json

tendrl-bug-id: https://github.com/Tendrl/monitoring-integration/issues/112

Dashboard status panel value fix

---

tendrl/monitoring_integration/grafana/create_dashboards.py

tendrl-bug-id: Tendrl/monitoring-integration#117
Signed-off-by: root <root@dhcp41-176.lab.eng.blr.redhat.com>

Skipping no_data alert in grafana

---

tendrl-monitoring-integration.spec

tendrl-bug-id: Tendrl/monitoring-integration#125

640 permission on service config file

---

etc/tendrl/monitoring-integration/grafana/dashboards/tendrl-gluster-at-a-glance.json
etc/tendrl/monitoring-integration/grafana/dashboards/tendrl-gluster-bricks.json
etc/tendrl/monitoring-integration/grafana/dashboards/tendrl-gluster-hosts.json
etc/tendrl/monitoring-integration/grafana/dashboards/tendrl-gluster-volumes.json

Made the graphs connected for null values and fixed healing counters

---

etc/tendrl/monitoring-integration/grafana/dashboards/tendrl-gluster-at-a-glance.json
etc/tendrl/monitoring-integration/grafana/dashboards/tendrl-gluster-volumes.json

Decimal correction for the counter panels

---

tendrl/monitoring_integration/grafana/create_alert_dashboard.py
tendrl/monitoring_integration/grafana/grafana_org_utils.py
tendrl/monitoring_integration/manager/__init__.py

tendrl-bug-id: Tendrl/monitoring-integration#133

Uploading default dashboards only in Main organisation

---

etc/tendrl/monitoring-integration/graphite/storage-schemas.conf.sample
tendrl-monitoring-integration.spec

tendrl-bug-id: Tendrl/monitoring-integration#95
Signed-off-by: anmolbabu <anmolbudugutta@gmail.com>

Increase graphite retention from default 1 day to 180 days

---

tendrl/monitoring_integration/alert/handlers/__init__.py
tendrl/monitoring_integration/alert/handlers/cluster/gluster/brick_utilization_handler.py
tendrl/monitoring_integration/alert/handlers/cluster/gluster/cluster_utilization_handler.py
tendrl/monitoring_integration/alert/handlers/cluster/gluster/volume_utilization_handler.py
tendrl/monitoring_integration/alert/handlers/node/cpu_handler.py
tendrl/monitoring_integration/alert/handlers/node/memory_handler.py
tendrl/monitoring_integration/alert/handlers/node/swap_handler.py
tendrl/monitoring_integration/alert/utils.py
tendrl/monitoring_integration/flows/new_cluster_dashboard/__init__.py
tendrl/monitoring_integration/flows/update_dashboard/__init__.py
tendrl/monitoring_integration/flows/update_dashboard/alert_utils.py
tendrl/monitoring_integration/grafana/alert.py
tendrl/monitoring_integration/grafana/cluster_detail.py
tendrl/monitoring_integration/grafana/create_alert_dashboard.py
tendrl/monitoring_integration/grafana/create_dashboards.py
tendrl/monitoring_integration/grafana/create_new_notification_channel.py
tendrl/monitoring_integration/grafana/dashboard.py
tendrl/monitoring_integration/grafana/grafana_org_utils.py
tendrl/monitoring_integration/grafana/utils.py
tendrl/monitoring_integration/grafana/webhook_receiver.py
tendrl/monitoring_integration/graphite/__init__.py
tendrl/monitoring_integration/graphite/graphite_utils.py
tendrl/monitoring_integration/manager/__init__.py
tendrl/monitoring_integration/objects/config/__init__.py
tendrl/monitoring_integration/objects/definition/__init__.py
tendrl/monitoring_integration/sync/__init__.py

Tendrl-bug-id: Tendrl/monitoring-integration#139

Fixed pep8 errors in monitoring-integration

---

.coveragerc
.landscape.yml

Tendrl-bug-id: Tendrl/monitoring-integration#141

Added .landscape.yml and .coveragerc file for Landscape check in PR

---

tendrl-monitoring-integration.spec

tendrl-bug-id: Tendrl/monitoring-integration#153

Changing permission of grafana.ini file

---

tendrl/monitoring_integration/graphite/__init__.py

tendrl-bug-id: Tendrl/monitoring-integration#145

Updating status in graphite if node status is deleted

---

tendrl/monitoring_integration/graphite/__init__.py
tendrl/monitoring_integration/graphite/graphite_utils.py

tendrl-bug-id: Tendrl/monitoring-integration#162

Upload resource in graphite only if the resource is not deleted

---

tendrl/monitoring_integration/graphite/__init__.py

tendrl-bug-id: Tendrl/monitoring-integration#178

Changing status mapping for resources

---

tendrl/monitoring_integration/graphite/__init__.py

tendrl-bug-id: Tendrl/monitoring-integration#159

Resolving lowercase and uppercase volume name issue in graphite

---

tendrl/monitoring_integration/manager/__init__.py

tendrl-bug-id: Tendrl/monitoring-integration#184

Adding KeyError and improving logging

---

tendrl/monitoring_integration/graphite/__init__.py

tendrl-bug-id: Tendrl/monitoring-integration#188

Using lowercase instead of uppercase

---

etc/tendrl/monitoring-integration/grafana/dashboards/tendrl-gluster-at-a-glance.json
etc/tendrl/monitoring-integration/grafana/dashboards/tendrl-gluster-bricks.json
etc/tendrl/monitoring-integration/grafana/dashboards/tendrl-gluster-hosts.json
etc/tendrl/monitoring-integration/grafana/dashboards/tendrl-gluster-volumes.json

Tendrl-bug-id: #186, #166, #164

Fixed Issue

---

tendrl/monitoring_integration/flows/new_cluster_dashboard/__init__.py
tendrl/monitoring_integration/flows/update_dashboard/__init__.py
tendrl/monitoring_integration/flows/update_dashboard/alert_utils.py
tendrl/monitoring_integration/grafana/create_alert_dashboard.py
tendrl/monitoring_integration/grafana/dashboard.py

tendrl-bug-id: Tendrl/monitoring-integration#158

Deleting alert dashboard if dashboard is empty

---

tendrl/monitoring_integration/alert/handlers/cluster/gluster/volume_utilization_handler.py
tendrl/monitoring_integration/alert/utils.py

Moved to node-agent
tendrl-bugid: Tendrl/monitoring-integratio#206

Removed find_volume_id function from volume handler

---

tendrl/monitoring_integration/alert/handlers/cluster/gluster/volume_utilization_handler.py

tendrl-bugid: Tendrl/monitoring-integration#208

Changed volume template to comapre grafana alert metrics

---

tendrl/monitoring_integration/alert/exceptions.py
tendrl/monitoring_integration/alert/handlers/__init__.py
tendrl/monitoring_integration/alert/utils.py
tendrl/monitoring_integration/grafana/alert.py

tendrl-bugid: Tendrl/monitoring-integration#204

Added context switch to grafana alert dashbaord while fetching alert

---

tendrl/monitoring_integration/flows/delete_resource_from_graphite/__init__.py
tendrl/monitoring_integration/flows/update_dashboard/__init__.py
tendrl/monitoring_integration/flows/update_dashboard/alert_utils.py

tendrl-bugid: Tendrl/monitoring-integration#238

Remove volume and brick dashboards from grafana when volume is deleted

---

etc/tendrl/monitoring-integration/grafana/dashboards/tendrl-gluster-at-a-glance.json
etc/tendrl/monitoring-integration/grafana/dashboards/tendrl-gluster-volumes.json

tendrl-bug-id: https://github.com/Tendrl/monitoring-integration/issues/244

Added new status values to grafana for geo-rep session

---

tendrl/monitoring_integration/graphite/__init__.py
tendrl/monitoring_integration/graphite/graphite_utils.py

tendrl-bug-id: Tendrl/gluster-integration#459

Enhanced to consider new georep session status values

---

tendrl/monitoring_integration/alert/handlers/cluster/gluster/brick_utilization_handler.py
tendrl/monitoring_integration/alert/handlers/cluster/gluster/cluster_utilization_handler.py
tendrl/monitoring_integration/alert/handlers/cluster/gluster/volume_utilization_handler.py
tendrl/monitoring_integration/alert/handlers/node/cpu_handler.py
tendrl/monitoring_integration/alert/handlers/node/memory_handler.py
tendrl/monitoring_integration/alert/handlers/node/swap_handler.py
tendrl/monitoring_integration/alert/utils.py

tendrl-bugid: Tendrl/monitoring-integration#226

alert utilization value is rounded and added units also

---

tendrl/monitoring_integration/flows/update_dashboard/__init__.py
tendrl/monitoring_integration/flows/update_dashboard/alert_utils.py

tendrl-bugid: Tendrl/monitoring-integration#241

Fixing bug in brick dashboard creation  when new volume is created

---

etc/tendrl/monitoring-integration/grafana/dashboards/tendrl-gluster-at-a-glance.json
etc/tendrl/monitoring-integration/grafana/dashboards/tendrl-gluster-bricks.json
etc/tendrl/monitoring-integration/grafana/dashboards/tendrl-gluster-hosts.json
etc/tendrl/monitoring-integration/grafana/dashboards/tendrl-gluster-volumes.json

tendrl-bug-id: https://github.com/Tendrl/monitoring-integration/issues/246

Units fix in Volume and Cluster dashboard

---

tendrl/monitoring_integration/objects/definition/monitoring_integration.yaml

Corected definition of georep sessions

---

tendrl/monitoring_integration/flows/update_dashboard/__init__.py
tendrl/monitoring_integration/flows/update_dashboard/alert_utils.py
tendrl/monitoring_integration/grafana/grafana_org_utils.py

Tendrl-bugid: Tendrl/monitoring-integration#249

Added context switch to alert_dashbsaord while deleting volume dashbaord

---

etc/tendrl/monitoring-integration/grafana/dashboards/tendrl-gluster-bricks.json

tendrl-bug-id https://github.com/Tendrl/monitoring-integration/issues/252

Changing utilization to mount_utilization in disk query

---

tendrl/monitoring_integration/objects/definition/monitoring_integration.yaml

tendrl-bug-id: Tendrl/monitoring-integration#271
Signed-off-by: Darshan N <darshan.n.2024@gmail.com>

push volume inode usage from etcd to graphite

---

etc/tendrl/monitoring-integration/grafana/dashboards/tendrl-gluster-at-a-glance.json
etc/tendrl/monitoring-integration/grafana/dashboards/tendrl-gluster-hosts.json
etc/tendrl/monitoring-integration/grafana/dashboards/tendrl-gluster-volumes.json

tendrl-bug-id: https://github.com/Tendrl/monitoring-integration/issues/279

Fixes cluster Id not showing up properly. when navigating to another page

---

etc/tendrl/monitoring-integration/grafana/dashboards/tendrl-gluster-volumes.json
tendrl/monitoring_integration/graphite/__init__.py

Tendrl-bug-id: https://github.com/Tendrl/monitoring-integration/issues/283
https://github.com/Tendrl/gluster-integration/issues/497

Fixed rebalance status

---

tendrl/monitoring_integration/grafana/create_dashboards.py

tendrl-bugid: Tendrl/monitoring-integration#289

Fix brick path bug in alert dashboard metric

---

tendrl/monitoring_integration/flows/delete_resource_from_graphite/__init__.py

tendrl-bugid: Tendrl/monitoring-integration#285

Deleting host panel from alert dashboard for peer disconnect

---

tendrl/monitoring_integration/flows/update_dashboard/__init__.py

tednrl-bugid: Tendrl/monitoring-integration#285

Fixing bug in deleting host dashbaord

---

etc/tendrl/monitoring-integration/grafana/dashboards/tendrl-gluster-volumes.json

tendrl-bug-id: https://github.com/Tendrl/monitoring-integration/issues/291

Fixing the rebalance counters

---

tendrl-monitoring-integration.spec

tendrl-bug-id: Tendrl/monitoring-integration/issues#295

Supress unwanted info during package update

---

etc/tendrl/monitoring-integration/grafana/dashboards/tendrl-gluster-at-a-glance.json
etc/tendrl/monitoring-integration/grafana/dashboards/tendrl-gluster-bricks.json
etc/tendrl/monitoring-integration/grafana/dashboards/tendrl-gluster-hosts.json
etc/tendrl/monitoring-integration/grafana/dashboards/tendrl-gluster-volumes.json

tendrl-bug-id: https://github.com/Tendrl/monitoring-integration/issues/297, https://github.com/Tendrl/monitoring-integration/issues/222

Added Description to the grafana panels and fixed heal counts

---

etc/tendrl/monitoring-integration/grafana/dashboards/tendrl-gluster-volumes.json

tendrl-bug-id: https://github.com/Tendrl/monitoring-integration/issues/300

Added heal pending count

---

etc/tendrl/monitoring-integration/grafana/dashboards/tendrl-gluster-volumes.json

tendrl-bug-id: https://github.com/Tendrl/monitoring-integration/issues/302

Adding units to the rebalance-size info

---

tendrl/monitoring_integration/graphite/__init__.py

Default cluster status as unhealthy if deleted due to TTL

---

etc/tendrl/monitoring-integration/grafana/dashboards/tendrl-gluster-at-a-glance.json
etc/tendrl/monitoring-integration/grafana/dashboards/tendrl-gluster-bricks.json
etc/tendrl/monitoring-integration/grafana/dashboards/tendrl-gluster-hosts.json
etc/tendrl/monitoring-integration/grafana/dashboards/tendrl-gluster-volumes.json

tendrl-bug-id: https://github.com/Tendrl/monitoring-integration/issues/307

Adding last time for the status in dashboards

---

tendrl/monitoring_integration/graphite/__init__.py
tendrl/monitoring_integration/graphite/graphite_utils.py

Changed the priority of logs to warning

---

etc/tendrl/monitoring-integration/grafana/dashboards/tendrl-gluster-bricks.json
etc/tendrl/monitoring-integration/grafana/dashboards/tendrl-gluster-volumes.json

tendrl-bug-id:https://github.com/Tendrl/monitoring-integration/issues/314

Added healing info at brick dashboard and removed from volume dashboard

---

tendrl/monitoring_integration/grafana/create_new_notification_channel.py

Result before:
```
HOME=/var/lib/tendrl /usr/bin/tendrl-monitoring-integration
...
Setup TendrlContext for namespace.tendrl
Load definitions (.yml) for namespace.tendrl.objects.TendrlContext 
8789
Traceback (most recent call last):
File "/usr/bin/tendrl-monitoring-integration", line 9, in <module>
load_entry_point('tendrl-monitoring-integration==1.5.5', 'console_scripts', 'tendrl-monitoring-integration')()
File "/usr/lib/python2.7/site-packages/tendrl/monitoring_integration/manager/__init__.py", line 181, in main
monitoring_integration_manager.start()
File "/usr/lib/python2.7/site-packages/tendrl/monitoring_integration/manager/__init__.py", line 46, in start
File "/usr/lib/python2.7/site-packages/tendrl/monitoring_integration/grafana/create_new_notification_channel.py", line 18, in …
```

Fixing typo

---

tendrl-monitoring-integration.spec

tendrl-bug-id: https://github.com/Tendrl/monitoring-integration/issues/319

Remove grafana hard dependency

---

Makefile
tendrl-monitoring-integration.spec

tendrl-bug-id: https://github.com/Tendrl/monitoring-integration/issues/335

Upgraded version of vonage plugin in grafana

---

tendrl/monitoring_integration/grafana/alert_utils.py

Fixed arguments list

---

tendrl-monitoring-integration.spec

Firewall configuration reload will be taken care by
tendrl-ansible
tendrl-bug-id: Tendrl/tendrl-ansible#49

Remove firewall configuration reload

---

etc/tendrl/monitoring-integration/grafana/dashboards/tendrl-gluster-bricks.json

tendrl-bug-id: https://github.com/Tendrl/monitoring-integration/issues/252

Bricks Dashboard: utilization panel name and description change

---

tendrl/monitoring_integration/grafana/alert_dashboard.py

tendrl-bug-id: Tendrl/monitoring-integration/issues/357

Make tendrl compatible with Grafana 5.x.x

---

tendrl/monitoring_integration/grafana/alert_utils.py

tendrl-bug-id : Tendrl/monitoring-integration#351

Fix: Issue with delete alert dashboard during unmanage

---

tendrl/monitoring_integration/grafana/alert_utils.py

tendrl-bug-id: Tendrl/monitoring-integration#354

Fixed issue with alert dashboard removal for whole cluster

---

tendrl/monitoring_integration/grafana/alert_dashboard.py
tendrl/monitoring_integration/grafana/constants.py
tendrl/monitoring_integration/sync/dashbaord_sync.py
tendrl/monitoring_integration/sync/gluster_cluster_details.py
tendrl/monitoring_integration/tests/grafana/test_alert_dashboard.py

tendrl-bug-id: Tendrl/monitoring-integration#354

Modified alert dashbaord creation logic

---

tendrl/monitoring_integration/alert/handlers/__init__.py
tendrl/monitoring_integration/alert/handlers/cluster/gluster_handler/brick_utilization_handler.py
tendrl/monitoring_integration/alert/handlers/cluster/gluster_handler/volume_utilization_handler.py
tendrl/monitoring_integration/alert/handlers/node/cpu_handler.py
tendrl/monitoring_integration/alert/handlers/node/memory_handler.py
tendrl/monitoring_integration/alert/handlers/node/swap_handler.py
tendrl/monitoring_integration/alert/utils.py
tendrl/monitoring_integration/flows/delete_monitoring_data/__init__.py
tendrl/monitoring_integration/flows/update_dashboard/__init__.py
tendrl/monitoring_integration/grafana/alert_dashboard.py
tendrl/monitoring_integration/grafana/alert_organization.py
tendrl/monitoring_integration/grafana/dashboard.py
tendrl/monitoring_integration/grafana/datasource.py
tendrl/monitoring_integration/grafana/utils.py
tendrl/monitoring_integration/graphite/__init__.py
tendrl/monitoring_integration/graphite/graphite_utils.py
tendrl/monitoring_integration/manager/__init__.py
tendrl/monitoring_integration/sync/dashbaord_sync.py
tendrl/monitoring_integration/sync/gluster_cluster_details.py
tendrl/monitoring_integration/tests/grafana/test_datasource.py
tendrl/monitoring_integration/webhook/webhook_receiver.py

tendrl-bug-id: Tendrl/monitoring-integration#354

Moved all statements in each gluster_cluster_details into try

---

tendrl/monitoring_integration/alert/handlers/__init__.py
tendrl/monitoring_integration/alert/handlers/cluster/gluster_handler/brick_utilization_handler.py
tendrl/monitoring_integration/alert/handlers/cluster/gluster_handler/volume_utilization_handler.py
tendrl/monitoring_integration/alert/handlers/node/cpu_handler.py
tendrl/monitoring_integration/alert/handlers/node/memory_handler.py
tendrl/monitoring_integration/alert/handlers/node/swap_handler.py
tendrl/monitoring_integration/flows/delete_monitoring_data/__init__.py
tendrl/monitoring_integration/flows/update_dashboard/__init__.py
tendrl/monitoring_integration/grafana/alert_dashboard.py
tendrl/monitoring_integration/grafana/alert_organization.py
tendrl/monitoring_integration/grafana/dashboard.py
tendrl/monitoring_integration/grafana/datasource.py
tendrl/monitoring_integration/grafana/utils.py
tendrl/monitoring_integration/graphite/__init__.py
tendrl/monitoring_integration/graphite/graphite_utils.py
tendrl/monitoring_integration/manager/__init__.py
tendrl/monitoring_integration/sync/dashbaord_sync.py
tendrl/monitoring_integration/sync/gluster_cluster_details.py
tendrl/monitoring_integration/tests/grafana/test_datasource.py
tendrl/monitoring_integration/webhook/webhook_receiver.py

Reverts Tendrl/monitoring-integration#364

Revert "Moved all statements in each gluster_cluster_details into try"

---

tendrl/monitoring_integration/grafana/alert_dashboard.py
tendrl/monitoring_integration/grafana/constants.py
tendrl/monitoring_integration/sync/dashbaord_sync.py
tendrl/monitoring_integration/sync/gluster_cluster_details.py
tendrl/monitoring_integration/tests/grafana/test_alert_dashboard.py

Reverts Tendrl/monitoring-integration#362

Revert "Modified alert dashbaord creation logic"

---

tendrl/monitoring_integration/alert/handlers/__init__.py
tendrl/monitoring_integration/alert/handlers/cluster/gluster_handler/brick_utilization_handler.py
tendrl/monitoring_integration/alert/handlers/cluster/gluster_handler/volume_utilization_handler.py
tendrl/monitoring_integration/alert/handlers/node/cpu_handler.py
tendrl/monitoring_integration/alert/handlers/node/memory_handler.py
tendrl/monitoring_integration/alert/handlers/node/swap_handler.py
tendrl/monitoring_integration/flows/delete_monitoring_data/__init__.py
tendrl/monitoring_integration/flows/update_dashboard/__init__.py
tendrl/monitoring_integration/grafana/alert_dashboard.py
tendrl/monitoring_integration/grafana/alert_organization.py
tendrl/monitoring_integration/grafana/dashboard.py
tendrl/monitoring_integration/grafana/datasource.py
tendrl/monitoring_integration/grafana/utils.py
tendrl/monitoring_integration/graphite/__init__.py
tendrl/monitoring_integration/graphite/graphite_utils.py
tendrl/monitoring_integration/manager/__init__.py
tendrl/monitoring_integration/sync/dashbaord_sync.py
tendrl/monitoring_integration/sync/gluster_cluster_details.py
tendrl/monitoring_integration/tests/grafana/test_datasource.py
tendrl/monitoring_integration/webhook/webhook_receiver.py

Chaning log priority

---

tendrl/monitoring_integration/sync/gluster_cluster_details.py

Tendrl/monitoring-integration/issues/375

Modified volume deleted flag check

---

tendrl/monitoring_integration/alert/handlers/node/cpu_handler.py
tendrl/monitoring_integration/alert/handlers/node/memory_handler.py
tendrl/monitoring_integration/alert/handlers/node/swap_handler.py
tendrl/monitoring_integration/tests/alert/handlers/node/test_cpu_handler.py
tendrl/monitoring_integration/tests/alert/handlers/node/test_memory_handler.py
tendrl/monitoring_integration/tests/alert/handlers/node/test_swap_handler.py

tendrl-bug-id: Tendrl/monitoring-integration#379

Passing integration_id with alerts to increment cluster node alert

---

tendrl/monitoring_integration/grafana/alert_dashboard.py

tendrl-bug-id: Tendrl/monitoring-integration#381

Compare exact resource_name with existing resource_name

---

tendrl/monitoring_integration/alert/handlers/cluster/gluster_handler/brick_utilization_handler.py
tendrl/monitoring_integration/alert/utils.py
tendrl/monitoring_integration/tests/alert/handlers/cluster/gluster_handler/test_brick_handler.py

tendrl-bug-id: Tendrl/monitoring-integration#384

Brick Utilization: threshold breached Alert needs to reference gluster volume name

---

tendrl/monitoring_integration/alert/utils.py

tendrl-bug-id: Tendrl/monitoring-integration#396

Remove import statements for node-agent objects

---

etc/tendrl/monitoring-integration/grafana/dashboards/tendrl-gluster-at-a-glance.json
etc/tendrl/monitoring-integration/grafana/dashboards/tendrl-gluster-bricks.json
etc/tendrl/monitoring-integration/grafana/dashboards/tendrl-gluster-volumes.json

tendrl-bug-id: Tendrl/monitoring-integration#383

huge numbers reported by grafana are given the proper units

---

etc/tendrl/monitoring-integration/grafana/dashboards/tendrl-gluster-bricks.json

tendrl-bug-id: Tendrl/monitoring-integration#383

Fix minor regression with huge number units fix

---

tendrl/monitoring_integration/alert/handlers/cluster/gluster_handler/brick_utilization_handler.py
tendrl/monitoring_integration/alert/handlers/cluster/gluster_handler/volume_utilization_handler.py
tendrl/monitoring_integration/alert/handlers/node/cpu_handler.py
tendrl/monitoring_integration/alert/handlers/node/memory_handler.py
tendrl/monitoring_integration/alert/handlers/node/swap_handler.py
tendrl/monitoring_integration/flows/delete_monitoring_data/__init__.py
tendrl/monitoring_integration/tests/alert/handlers/cluster/gluster_handler/test_brick_handler.py
tendrl/monitoring_integration/tests/alert/handlers/cluster/gluster_handler/test_volume_handler.py
tendrl/monitoring_integration/tests/alert/handlers/node/test_cpu_handler.py
tendrl/monitoring_integration/tests/alert/handlers/node/test_memory_handler.py
tendrl/monitoring_integration/tests/alert/handlers/node/test_swap_handler.py

Improve alert messages
tendrl-bug-id:Tendrl/monitoring-integration/issues/406

Improve alert messages

---

tendrl/monitoring_integration/flows/delete_monitoring_data/__init__.py
tendrl/monitoring_integration/flows/setup_cluster_alias/__init__.py
tendrl/monitoring_integration/objects/definition/monitoring_integration.yaml

tendrl-bug-id: Tendrl/commons#888

Added flow SetupClusterAlias for creating a cluster alias in graphite

---

tendrl/monitoring_integration/graphite/graphite_utils.py
tendrl/monitoring_integration/sync/__init__.py

tendrl-bug-id: Tendrl/monitoring-integration#399

Creating short name link while sync

---

tendrl/monitoring_integration/alert/handlers/cluster/gluster_handler/brick_utilization_handler.py
tendrl/monitoring_integration/alert/handlers/cluster/gluster_handler/volume_utilization_handler.py
tendrl/monitoring_integration/alert/handlers/node/cpu_handler.py
tendrl/monitoring_integration/alert/handlers/node/memory_handler.py
tendrl/monitoring_integration/alert/handlers/node/swap_handler.py
tendrl/monitoring_integration/alert/utils.py
tendrl/monitoring_integration/grafana/alert_dashboard.py
tendrl/monitoring_integration/tests/alert/handlers/cluster/gluster_handler/brick_alert_error.json
tendrl/monitoring_integration/tests/alert/handlers/cluster/gluster_handler/brick_alert_info.json
tendrl/monitoring_integration/tests/alert/handlers/cluster/gluster_handler/test_brick_handler.py
tendrl/monitoring_integration/tests/alert/handlers/cluster/gluster_handler/test_volume_handler.py
tendrl/monitoring_integration/tests/alert/handlers/cluster/gluster_handler/volume_alert_error.json
tendrl/monitoring_integration/tests/alert/handlers/cluster/gluster_handler/volume_alert_info.json
tendrl/monitoring_integration/tests/alert/handlers/node/cpu_alert_error.json
tendrl/monitoring_integration/tests/alert/handlers/node/cpu_alert_info.json
tendrl/monitoring_integration/tests/alert/handlers/node/memory_alert_error.json
tendrl/monitoring_integration/tests/alert/handlers/node/memory_alert_info.json
tendrl/monitoring_integration/tests/alert/handlers/node/swap_alert_error.json
tendrl/monitoring_integration/tests/alert/handlers/node/swap_alert_info.json
tendrl/monitoring_integration/tests/alert/handlers/node/test_cpu_handler.py
tendrl/monitoring_integration/tests/alert/handlers/node/test_memory_handler.py
tendrl/monitoring_integration/tests/alert/handlers/node/test_swap_handler.py

tendrl-bug-id: Tendrl/monitoring-integration#403

Adding cluster_short_name in alert message instead of integration_id

---

etc/tendrl/monitoring-integration/grafana/dashboards/tendrl-gluster-at-a-glance.json
etc/tendrl/monitoring-integration/grafana/dashboards/tendrl-gluster-bricks.json
etc/tendrl/monitoring-integration/grafana/dashboards/tendrl-gluster-hosts.json
etc/tendrl/monitoring-integration/grafana/dashboards/tendrl-gluster-volumes.json

tendrl-bug-id: Tendrl/monitoring-integration#399

Addition of short_name changes to grafana json

---

tendrl/monitoring_integration/flows/delete_monitoring_data/__init__.py
tendrl/monitoring_integration/objects/definition/monitoring_integration.yaml

tendrl-bug-id: Tendrl/monitoring-integration#416

Fixes around un-manage flow and definition file

---

tendrl/monitoring_integration/grafana/notification_channel.py
tendrl/monitoring_integration/webhook/webhook_receiver.py

tendrl-bug-id: Tendrl/monitoring-integration#414

Modified notification channel's hostname assigning logic 

---

tendrl/monitoring_integration/grafana/alert_dashboard.py
tendrl/monitoring_integration/grafana/alert_utils.py
tendrl/monitoring_integration/grafana/constants.py
tendrl/monitoring_integration/sync/dashbaord_sync.py
tendrl/monitoring_integration/sync/gluster_cluster_details.py
tendrl/monitoring_integration/tests/grafana/dashboard.json
tendrl/monitoring_integration/tests/grafana/test_alert_dashboard.py

tendrl-bug-id: Tendrl/monitoring-integration#354

Optimizing alert dashboard creation logic

---

tendrl/monitoring_integration/sync/dashbaord_sync.py
tendrl/monitoring_integration/sync/gluster_cluster_details.py

Fixing issue in monitoring-integration

---

tendrl/monitoring_integration/grafana/alert_utils.py

Added a check for empty alert dashboard

---

tendrl/monitoring_integration/grafana/alert_dashboard.py
tendrl/monitoring_integration/grafana/constants.py
tendrl/monitoring_integration/sync/dashbaord_sync.py

Corrected checking of sds_name
tendrl-bug-id: Tendrl/monitoring-integration#425

Corrected checking of sds_name

---

tendrl/monitoring_integration/sync/gluster_cluster_details.py

tendrl-bug-id: Tendrl/monitoring-integration#426

Fixed issue in collecting brick details

---

tendrl/monitoring_integration/graphite/__init__.py

tendrl-bug-id: Tendrl/monitoring-integration#429
bugzilla-id: 1571755

Grafana shows short_name as well as integration_id of same cluster

---

tendrl/monitoring_integration/graphite/__init__.py
tendrl/monitoring_integration/sync/gluster_cluster_details.py

tendrl-bug-id: Tendrl/monitoring-integration#431
bugzilla-id: 1564510

Grafana dashboards with new nodes are created before user initiates cluster expansion

---

tendrl-monitoring-integration.spec
tendrl/monitoring_integration/alert/handlers/__init__.py

tendrl-bug-id: Tendrl/monitoring-integration#433
bugzilla-id: 1572052

Added integration_id in utilization alert message log

---

etc/tendrl/monitoring-integration/monitoring-integration.conf.yaml.sample
tendrl/monitoring_integration/flows/delete_monitoring_data/__init__.py

tendrl-bug-id: Tendrl/monitoring-integration#436

Archive graphite data in same device

---

tendrl/monitoring_integration/sync/dashbaord_sync.py

tendrl-bug-id: Tendrl/monitoring-integration#438
bugzilla: 1573481

Fixing alert dashboard creation problem when more than one clusters are managed

---

tendrl/monitoring_integration/alert/handlers/cluster/gluster_handler/brick_utilization_handler.py
tendrl/monitoring_integration/alert/handlers/cluster/gluster_handler/volume_utilization_handler.py
tendrl/monitoring_integration/alert/handlers/node/cpu_handler.py
tendrl/monitoring_integration/alert/handlers/node/memory_handler.py
tendrl/monitoring_integration/alert/handlers/node/swap_handler.py
tendrl/monitoring_integration/grafana/alert_dashboard.py
tendrl/monitoring_integration/grafana/constants.py

tendrl-bug-id: Tendrl/monitoring-integration/issues/442
bugzilla: 1575040

Alert dashbaord is not raising alert when cluster is import with short_name

---

etc/tendrl/monitoring-integration/grafana/dashboards/tendrl-gluster-at-a-glance.json
etc/tendrl/monitoring-integration/grafana/dashboards/tendrl-gluster-hosts.json
etc/tendrl/monitoring-integration/grafana/dashboards/tendrl-gluster-volumes.json

tendrl-bug-id: Tendrl/monitoring-integration#445
bugzilla: 1574512

Number not shown for the values which has got threshold set

---

tendrl/monitoring_integration/graphite/__init__.py

tendrl-bug-id: Tendrl/monitoring-integration#447
bugzilla: 1574938

Volume with name 'None' listed in grafana dashboard

---

setup.py
tendrl-monitoring-integration.spec
tendrl/monitoring_integration/webhook/webhook_receiver.py

tendrl-bug-id: Tendrl/monitoring-integration#451

Use cherrypy instead of development server for grafana alerts web callback

---

tendrl/monitoring_integration/graphite/__init__.py

tendrl-bug-id: Tendrl/monitoring-integration#452
bugzilla: 1560875

closing carbon-cache socket connections properly

---

tendrl/monitoring_integration/grafana/alert_dashboard.py

tendrl-bug-id: Tendrl/monitoring-integration#458
bugzilla: 1564175

False alerts when brick utilization breached 90%

---

etc/tendrl/monitoring-integration/grafana/dashboards/tendrl-gluster-at-a-glance.json
etc/tendrl/monitoring-integration/grafana/dashboards/tendrl-gluster-hosts.json
etc/tendrl/monitoring-integration/grafana/dashboards/tendrl-gluster-volumes.json

tendrl-bug-id: Tendrl/monitoring-integration#462
bugzilla: 1578009

brick status tool-tip differs with real values

---

tendrl/monitoring_integration/alert/handlers/__init__.py
tendrl/monitoring_integration/webhook/webhook_receiver.py

tendrl-bug-id: Tendrl/monitoring-integration#458
bugzilla: 1564175

Fixing false alert issue

---

tendrl/monitoring_integration/webhook/webhook_receiver.py

tendrl-bug-id: Tendrl/monitoring-integration#465
Bugzilla-id: https://bugzilla.redhat.com/1581636

Removed super.stop() call as threading.Thread class doesnt have

---

tendrl/monitoring_integration/flows/delete_monitoring_data/__init__.py

tendrl-bug-id: Tendrl/monitoring-integration#468
bugzilla: 1570048

unmanaged task always fails after import failure

---

tendrl/monitoring_integration/flows/delete_monitoring_data/__init__.py
tendrl/monitoring_integration/manager/__init__.py
tendrl/monitoring_integration/webhook/webhook_receiver.py

bugzilla: 1582375
tendrl-bug-id: Tendrl/commons#819

Added logic to remove telemetry data based on flag passed

---

tendrl/monitoring_integration/alert/handlers/node/cpu_handler.py
tendrl/monitoring_integration/alert/handlers/node/memory_handler.py
tendrl/monitoring_integration/alert/handlers/node/swap_handler.py

tendrl-bug-id: Tendrl/monitoring-integration#470
bugzilla: 1583171

Utilization notifications use integration id instead of cluster name

---

etc/tendrl/monitoring-integration/grafana/dashboards/tendrl-gluster-at-a-glance.json
etc/tendrl/monitoring-integration/grafana/dashboards/tendrl-gluster-bricks.json
etc/tendrl/monitoring-integration/grafana/dashboards/tendrl-gluster-hosts.json
etc/tendrl/monitoring-integration/grafana/dashboards/tendrl-gluster-volumes.json

tendrl-bug-id: Tendrl/monitoring-integration#472
bugzilla: 1579516

Remove all Trend keyword from grafana

---

tendrl/monitoring_integration/flows/delete_monitoring_data/__init__.py

bugzilla: 1582375
tendrl-bug-id: Tendrl/commons#819

Changed to not not delete the telemetry data by default

---

etc/tendrl/monitoring-integration/grafana/dashboards/tendrl-gluster-volumes.json

tendrl-bug-id: Tendrl/monitoring-integration#472
bugzilla: 1579516

fix - Remove all Trend keyword from grafana

---

tendrl/monitoring_integration/grafana/alert_dashboard.py

tendrl-bug-id: #480
bugzilla: 1585116

Fix Grafana alerts dashboard when string 'tendrl' is present in hostname

---

tendrl/monitoring_integration/alert/handlers/cluster/gluster_handler/brick_utilization_handler.py
tendrl/monitoring_integration/alert/handlers/cluster/gluster_handler/volume_utilization_handler.py
tendrl/monitoring_integration/alert/handlers/node/cpu_handler.py
tendrl/monitoring_integration/alert/handlers/node/memory_handler.py
tendrl/monitoring_integration/alert/handlers/node/swap_handler.py

tendrl-bug-id: Tendrl/monitoring-integration#484
bugzilla: 1564175

Changing date format of grafana utilization alert

---

tendrl/monitoring_integration/graphite/__init__.py
tendrl/monitoring_integration/sync/gluster_cluster_details.py

tendrl-bug-id: Tendrl/monitoring-integration#486
bugzilla: 1518610

Deleted volume details are not cleared from grafana dashbaord

---

tendrl/monitoring_integration/tests/alert/handlers/cluster/gluster_handler/brick_alert_error.json
tendrl/monitoring_integration/tests/alert/handlers/cluster/gluster_handler/brick_alert_info.json
tendrl/monitoring_integration/tests/alert/handlers/cluster/gluster_handler/test_brick_handler.py
tendrl/monitoring_integration/tests/alert/handlers/cluster/gluster_handler/test_volume_handler.py
tendrl/monitoring_integration/tests/alert/handlers/cluster/gluster_handler/volume_alert_error.json
tendrl/monitoring_integration/tests/alert/handlers/cluster/gluster_handler/volume_alert_info.json
tendrl/monitoring_integration/tests/alert/handlers/node/cpu_alert_error.json
tendrl/monitoring_integration/tests/alert/handlers/node/cpu_alert_info.json
tendrl/monitoring_integration/tests/alert/handlers/node/memory_alert_error.json
tendrl/monitoring_integration/tests/alert/handlers/node/memory_alert_info.json
tendrl/monitoring_integration/tests/alert/handlers/node/swap_alert_error.json
tendrl/monitoring_integration/tests/alert/handlers/node/swap_alert_info.json
tendrl/monitoring_integration/tests/alert/handlers/node/test_cpu_handler.py
tendrl/monitoring_integration/tests/alert/handlers/node/test_memory_handler.py
tendrl/monitoring_integration/tests/alert/handlers/node/test_swap_handler.py
tendrl/monitoring_integration/tests/objects/alert_organization/test_init.py
tendrl/monitoring_integration/tests/test_init.py

tendrl-bug-id: Tendrl/monitoring-integration#488

Fixed testcase failures in monitoring-integration

---

etc/tendrl/monitoring-integration/grafana/dashboards/tendrl-gluster-at-a-glance.json

tendrl-bug-id: Tendrl/monitoring-integration#490
bugzilla: 1581789

Update the tooltip for connection trend

---

etc/tendrl/monitoring-integration/grafana/dashboards/tendrl-gluster-at-a-glance.json
etc/tendrl/monitoring-integration/grafana/dashboards/tendrl-gluster-bricks.json
etc/tendrl/monitoring-integration/grafana/dashboards/tendrl-gluster-volumes.json

tendrl-bug-id: Tendrl/monitoring-integration#478
bugzilla: 1581736

IOPS Single stat panel need to changed to graph panel

---

Makefile
tendrl-monitoring-integration.spec

rel_prep 1.6.3-6

---

etc/tendrl/monitoring-integration/grafana/dashboards/tendrl-gluster-at-a-glance.json

tendrl-bug-id: Tendrl/monitoring-integration#499
bugzilla: 1592991

Changed heading for connection panel in cluster dashboard

---

etc/tendrl/monitoring-integration/grafana/dashboards/tendrl-gluster-at-a-glance.json

tendrl-bug-id: Tendrl/monitoring-integration#501
bugzilla: 1592992

Added units for Throughput panel in cluster dashboard

---

etc/tendrl/monitoring-integration/grafana/dashboards/tendrl-gluster-hosts.json

tendrl-bug-id: Tendrl/monitoring-integration#511
bugzilla: 1595016

Panel heading change form Disk IO panel to Disk IO Latency

---

etc/tendrl/monitoring-integration/grafana/dashboards/tendrl-gluster-hosts.json

tendrl-bug-id: Tendrl/monitoring-integration#508
bugzilla: 1595015

Disk load panel is changed to Disk throughput

---

etc/tendrl/monitoring-integration/graphite/carbon.conf.sample

tendrl-bug-id: Tendrl/monitoring-integration#505
bugzilla: 1596862

Increase carbon cache file creation count

---

tendrl/monitoring_integration/graphite/__init__.py
tendrl/monitoring_integration/sync/__init__.py

tendrl-bug-id: Tendrl/monitoring-integration#504
bugzilla: 1596862

   Optimizing carbon-cache utilization by pushing list of metrics in single HTTP call

---

etc/tendrl/monitoring-integration/grafana/dashboards/tendrl-gluster-hosts.json

- Disk Operation to Disk IOPS
- IOPS to Brick IOPS
tendrl-bug-id: Tendrl/monitoring-integration#515
bugzilla: 1595013

Changes IOPS panel name in host dashboard

---

etc/tendrl/monitoring-integration/grafana/dashboards/tendrl-gluster-at-a-glance.json

tendrl-bug-id: Tendrl/monitoring-integration#513
bugzilla: 1595005

Ping latency metric tool-tip change

---

tendrl-monitoring-integration.service

tendrl-bug-id: Tendrl/monitoring-integration/issues/519
bugzilla: 1559456

Removing documentation link from service file

---

etc/tendrl/monitoring-integration/grafana/dashboards/tendrl-gluster-bricks.json

tendrl-bug-id: Tendrl/monitoring-integration#507
bugzilla: 1595052

Changing units for throughput and latency panel in disk dashboard

---

etc/tendrl/monitoring-integration/grafana/dashboards/tendrl-gluster-at-a-glance.json
etc/tendrl/monitoring-integration/grafana/dashboards/tendrl-gluster-bricks.json
etc/tendrl/monitoring-integration/grafana/dashboards/tendrl-gluster-hosts.json
etc/tendrl/monitoring-integration/grafana/dashboards/tendrl-gluster-volumes.json

tendrl-bug-id: Tendrl/monitoring-integration#522
bugzilla: 1594862

Fixed threshold values in grafana

---

etc/tendrl/monitoring-integration/grafana/dashboards/tendrl-gluster-at-a-glance.json
etc/tendrl/monitoring-integration/grafana/dashboards/tendrl-gluster-bricks.json
etc/tendrl/monitoring-integration/grafana/dashboards/tendrl-gluster-hosts.json
etc/tendrl/monitoring-integration/grafana/dashboards/tendrl-gluster-volumes.json

tendrl-bug-id: Tendrl/monitoring-integration#497
bugzilla: 1587804

fix description for the IOPS panels

---

tendrl/monitoring_integration/flows/delete_resource_from_graphite/graphite_delete_utils.py

tendr-bug-id: Tendrl/monitoring-integration#526
bugzilla: 1599691

Removing node details from graphite under volume when all bricks are delete for that node delete for that node

---

tendrl/monitoring_integration/graphite/__init__.py
tendrl/monitoring_integration/graphite/graphite_utils.py

tendrl-bug-id: Tendrl/monitoring-integration#530
bugzilla: 1603175

Fixing an issue of geo-replication count not shown in grafana

---

Makefile
tendrl-monitoring-integration.spec

rel_prep/1.6.3-9

---

etc/tendrl/monitoring-integration/grafana/dashboards/tendrl-gluster-at-a-glance.json
etc/tendrl/monitoring-integration/grafana/dashboards/tendrl-gluster-bricks.json
etc/tendrl/monitoring-integration/grafana/dashboards/tendrl-gluster-hosts.json
etc/tendrl/monitoring-integration/grafana/dashboards/tendrl-gluster-volumes.json

tendrl-bug-id: Tendrl/monitoring-integration#534
bugzilla: 1581718, 1549146

Weekly growth and weeks remaining is not accurate

---

Makefile
tendrl-monitoring-integration.spec

rel_prep/1.6.3-10

---

etc/tendrl/monitoring-integration/grafana/dashboards/tendrl-gluster-at-a-glance.json
etc/tendrl/monitoring-integration/grafana/dashboards/tendrl-gluster-hosts.json

tendrl-bug-id: Tendrl/monitoring-integration#538
bugzilla: 1581718

changing the validation order of weeks remaining

---

etc/tendrl/monitoring-integration/grafana/dashboards/tendrl-gluster-at-a-glance.json
etc/tendrl/monitoring-integration/grafana/dashboards/tendrl-gluster-bricks.json
etc/tendrl/monitoring-integration/grafana/dashboards/tendrl-gluster-hosts.json
etc/tendrl/monitoring-integration/grafana/dashboards/tendrl-gluster-volumes.json

tendrl-bug-id: Tendrl/monitoring-integration#538
bugzilla: 1581718

[Bug fix] Negative value in weeks remaining

---

Makefile
tendrl-monitoring-integration.spec

rel_prep/1.6.3-11

---

etc/tendrl/monitoring-integration/grafana/dashboards/tendrl-gluster-hosts.json

tendrl-bug-id: Tendrl/monitoring-integration#547
bugzilla: 1613998

Adding all health states of host in host dashboard

---

etc/tendrl/monitoring-integration/grafana/dashboards/tendrl-gluster-bricks.json

tendrl-bug-id: Tendrl/monitoring-integration#551
bugzilla: 1613526

Adding all brick states in Status panel on Brick dashboard 

---

etc/tendrl/monitoring-integration/grafana/dashboards/tendrl-gluster-volumes.json

tendrl-bug-id: Tendrl/monitoring-integration#553
bugzilla: 1614217

Added all possible states of volumes in status panel on volume dashboard

---

etc/tendrl/monitoring-integration/grafana/dashboards/tendrl-gluster-at-a-glance.json

tendrl-bug-id: Tendrl/monitoring-integration#562
bugzilla: 1613492

Added units in Ping Latency panel

---

etc/tendrl/monitoring-integration/grafana/dashboards/tendrl-gluster-bricks.json

bugzilla: 1613705
tendrl-bug-id: Tendrl/monitoring-integration#566

Modified description of IOPS chart in "Disk Load" section of Brick dashboard

---

etc/tendrl/monitoring-integration/grafana/dashboards/tendrl-gluster-hosts.json

bugzilla: 1614001
tendrl-bug-id: Tendrl/monitoring-integration#568

Modified memory utilization panel on Host dashboard

---

etc/tendrl/monitoring-integration/grafana/dashboards/tendrl-gluster-volumes.json

bugzilla: 1614373
tendrl-bug-id: Tendrl/monitoring-integration#572

Modified description of charts from profiling information section of volume dashboard

---

etc/tendrl/monitoring-integration/grafana/dashboards/tendrl-gluster-volumes.json

tendrl-bug-id: Tendrl/monitoring-integration#559
bugzilla: 1614270

Modified description of IOPS panel in volume dashbaord

---

etc/tendrl/monitoring-integration/grafana/dashboards/tendrl-gluster-bricks.json

tendrl-bug-id: Tendrl/monitoring-integration#549
bugzilla: 1613729

Removed mount-point utilization panel from disk load

---

etc/tendrl/monitoring-integration/grafana/dashboards/tendrl-gluster-at-a-glance.json
etc/tendrl/monitoring-integration/grafana/dashboards/tendrl-gluster-hosts.json

bugzilla: 1614005
tendrl-bug-id: Tendrl/monitoring-integration#564

Removed Weeks Remaining and growth rate  panels from  Host dashboard and cluster dashboard

---

tendrl/monitoring_integration/grafana/dashboard_utils.py

tendrl-bug-id: Tendrl/monitoring-integration#580
bugzilla: 1656057, 1656064

Utilization alerts are not working- 1656057, 1656064

---

etc/tendrl/monitoring-integration/grafana/dashboards/tendrl-gluster-at-a-glance.json
etc/tendrl/monitoring-integration/grafana/dashboards/tendrl-gluster-hosts.json
etc/tendrl/monitoring-integration/grafana/dashboards/tendrl-gluster-volumes.json
etc/tendrl/monitoring-integration/graphite/graphite-web.conf.sample
tendrl/monitoring_integration/alert/handlers/cluster/gluster_handler/brick_utilization_handler.py
tendrl/monitoring_integration/flows/delete_resource_from_graphite/graphite_delete_utils.py
tendrl/monitoring_integration/grafana/alert_dashboard.py
tendrl/monitoring_integration/grafana/alert_utils.py
tendrl/monitoring_integration/grafana/constants.py
tendrl/monitoring_integration/graphite/__init__.py
tendrl/monitoring_integration/graphite/graphite_utils.py
tendrl/monitoring_integration/sync/dashbaord_sync.py
tendrl/monitoring_integration/sync/gluster_cluster_details.py
tendrl/monitoring_integration/tests/graphite/result.json
tendrl/monitoring_integration/upgrades/delete_dashboards.py

tendrl-bug-id: Tendrl/monitoring-integration#584
bugzilla: 1660779

After migration to graphite-1.1.4 the brick specific dashboards are not visible in grafana

---

tendrl/monitoring_integration/grafana/alert_dashboard.py
tendrl/monitoring_integration/grafana/dashboard_utils.py
tendrl/monitoring_integration/grafana/datasource_utils.py
tendrl/monitoring_integration/grafana/grafana_org_utils.py
tendrl/monitoring_integration/grafana/notification_channel.py
tendrl/monitoring_integration/graphite/__init__.py
tendrl/monitoring_integration/graphite/graphite_utils.py
tendrl/monitoring_integration/tests/objects/config/test_config.py
tendrl/monitoring_integration/tests/objects/definition/test_definition.py
tendrl/monitoring_integration/tests/objects/trigger/test_trigger.py
tendrl/monitoring_integration/upgrades/delete_dashboards.py

bugzilla: 1679060
tendrl-bug-id: Tendrl/monitoring-integration#591

tendrl-monitoring-integration service fails to start with HTTPS is enabled

---

tendrl/monitoring_integration/manager/__init__.py
tendrl/monitoring_integration/sync/__init__.py

tendrl-bug-id: Tendrl/monitoring-integration#593
bugzilla: 1688630

Added tendrl/integration/monitoring tag update in sync

---

tendrl/monitoring_integration/flows/setup_cluster_alias/__init__.py
tendrl/monitoring_integration/graphite/graphite_utils.py
tendrl/monitoring_integration/upgrades/delete_dashboards.py
tendrl/monitoring_integration/upgrades/utils.py

tendrl-bug-id:Tendrl/monitoring-integration#595
bugzilla: 1647322

Assigning ownership for carbon user
