tendrl/monitoring_integration/flows/create_alert_dashboard/__init__.py
tendrl/monitoring_integration/flows/update_dashboard/__init__.py
tendrl/monitoring_integration/manager/__init__.py
tendrl/monitoring_integration/objects/definition/monitoring_integration.yaml

Also the node tagging with `tendrl/integration/monitoring` was mising.
Added the logic to add the tag for the server node with this.
tendrl-bug-id: Tendrl/monitoring-integration#54

Corrected definitions for the flows

---

tendrl/monitoring_integration/objects/definition/monitoring_integration.yaml

tendrl-bug-id: Tendrl/node-agent#602

Added parameter `TendrlContext.cluster_name` for the flow

---

tendrl/monitoring_integration/alert/handlers/__init__.py

Currently, we are using a flag called notify_only_ui to differentiate
notification from alert. But we should introduce a flags in alerting messages
to differentiate alert from notification. no need any flag in notification
messages.

Added alert codition to differentiate alert from notifications

---

tendrl/monitoring_integration/flows/delete_resource_from_graphite/__init__.py
tendrl/monitoring_integration/flows/update_graphite/__init__.py
tendrl/monitoring_integration/objects/definition/monitoring_integration.yaml

Tendrl-bug-id: Tendrl/monitoring-integration#148

Delete graphite data when resource gets deleted

---

tendrl/monitoring_integration/alert/handlers/__init__.py
tendrl/monitoring_integration/alert/handlers/cluster/gluster/brick_utilization_handler.py
tendrl/monitoring_integration/alert/handlers/cluster/gluster/cluster_utilization_handler.py
tendrl/monitoring_integration/alert/handlers/cluster/gluster/volume_utilization_handler.py
tendrl/monitoring_integration/alert/handlers/node/cpu_handler.py
tendrl/monitoring_integration/alert/handlers/node/memory_handler.py
tendrl/monitoring_integration/alert/handlers/node/swap_handler.py
tendrl/monitoring_integration/grafana/webhook_receiver.py

tendrl-bugid: Tendrl/monitoring-integration#218
tendrl-bugid: Tendrl/monitoring-integration#216

Modifying alerting logic based on alert classifications

---

tendrl-monitoring-integration.spec

The latest version available in grafana repo does not works
as expected with tendrl. This patch will lock down the
grafana version to 4.5.2
tendrl-bugid: Tendrl/monitoring-integration#224

Lock down the grafana required version to 4.5.2

---

tendrl/monitoring_integration/graphite/__init__.py

Earlier the counters were getting initialized only once and not at
cluster level. So effectively next set of cluster would accumulate
the previous cluster's count values as well. This skrews up the georep
session counts in grafana dashboard if multiple clusters are imported.
tendrl-bug-id: Tendrl/monitoring-integration#257

Corrected the initialization of cluster specific georep counts

---

etc/tendrl/monitoring-integration/graphite/carbon.conf.sample

This info is something of debug leval and its flooding
the listener.log file. So setting the attribute
LOG_LISTENER_CONNECTIONS to false in carbon conf file
tendrl-bug-id: Tendrl/monitoring-integration#262
Signed-off-by: Darshan N <darshan.n.2024@gmail.com>

Disable logging of successful connections

---

tendrl/monitoring_integration/graphite/__init__.py

If there are not georep session setup for a volume, the error message
gets looged again and again each sync time. Removed the same as its
un-wanted noise in the log files.

Removed unwanted error message logged while no georep details for vol

---

etc/tendrl/monitoring-integration/monitoring-integration.conf.yaml.sample

tendrl-bug-id: Tendrl/monitoring-integration#339
Signed-off-by: GowthamShanmugaSundaram <gshanmug@redhat.com>

grafana_host and grafana_port is missing in monitoring_integration.conf

---

tendrl/monitoring_integration/flows/delete_monitoring_data/__init__.py

While un-manage cluster, the archive location was earlier being
communicated through a notification. The same is changed to just
log as an event as un-manage is always a user triggered action
and and event with archive location details is sufficient
tendrl-bug-id: Tendrl/notifier#157

Changed the eventing of archive location of monitoring data

---

etc/tendrl/monitoring-integration/grafana/dashboards/tendrl-gluster-bricks.json
tendrl/monitoring_integration/graphite/__init__.py

tendrl-bug-id: Tendrl/monitoring-integration#365

Brick status value mapping change

---

tendrl/monitoring_integration/alert/utils.py

tendrl-bug-id: Tendrl/monitoring-integration#403

Using integration_id in alert message when cluster_short_name is None

---

Makefile

tendrl-bug-id: Tendrl/monitoring-integration#419

Lock down to 1.0.6 version of grafana-vonage plugin

---

etc/systemd/system/carbon-cache.service.d/serviceparam.conf

tendrl-bug-id: Tendrl/monitoring-integration#452
bugzilla: 1560875
Increasing the Max no of open fds to 500000 to accomodate the connections when operating at scale. Have seen that when server is loaded, it takes time to close the connections and the open fds increases steadily. Given a higher number to make sure we are not running out of fds.
See also Related PRs (1 ) Tendrl/monitoring-integration#493 (Specfile changes to accomodate this PR) (2) Tendrl/tendrl-ansible#105 (Systemd daemon reload after placing the unit file)
Signed-off-by: Nishanth Thomas <nthomas@redhat.com>

Increase Max no of open Fds to a higher number

---

tendrl-monitoring-integration.spec

tendrl-bug-id: Tendrl/monitoring-integration#452
bugzilla: 1560875
See also Related PRs (1 )https://github.com/Tendrl/monitoring-integration/pull/492 (systemd dropin unit file increase the no of Max open Fds) (2) https://github.com/Tendrl/tendrl-ansible/pull/105 (Systemd daemon reload after placing the unit file)
Signed-off-by: Nishanth Thomas <nthomas@redhat.com>

Updated the specfile to manage conf file to handle carbon-cache socket connections

---

etc/tendrl/monitoring-integration/grafana/dashboards/tendrl-gluster-bricks.json

tendrl-bug-id: Tendrl/monitoring-integration#543
bugzilla: 1613527

Description of Capacity Available panel on Brick dashboards refers to a volume by mistake

---

etc/tendrl/monitoring-integration/grafana/dashboards/tendrl-gluster-at-a-glance.json
etc/tendrl/monitoring-integration/grafana/dashboards/tendrl-gluster-hosts.json
etc/tendrl/monitoring-integration/grafana/dashboards/tendrl-gluster-volumes.json

tendrl-bug-id: Tendrl/monitoring-integration#545
bugzilla: 1614000

"Bricks" and "Brick Status" panels on Host and Volume dashboards doesn't use the same definition of brick state 

---

etc/tendrl/monitoring-integration/grafana/dashboards/tendrl-gluster-hosts.json

tendrl-bug-id: Tendrl/monitoring-integration#556
bugzilla: 1614012

Updated description for Disk IOPS on host dashboard

---

etc/tendrl/monitoring-integration/grafana/dashboards/tendrl-gluster-volumes.json

bugzilla: 1614263
tendrl-bug-id: Tendrl/monitoring-integration#570

Removed Subvolume panel from Volume dashboard

---

etc/tendrl/monitoring-integration/grafana/dashboards/tendrl-gluster-bricks.json

tendrl-bug-id: Tendrl/monitoring-integration#555
bugzilla: 1613529

Removed inactive link from healing panel of Brick dashboard

---

setup.py
tendrl/monitoring_integration/upgrades/delete_dashboards.py

tendrl-bug-id: Tendrl/monitoring-integration#575
bugzilla: 1631260

Created script to delete grafana dashboards

---

etc/grafana/grafana.ini
tendrl/monitoring_integration/grafana/alert_organization.py
tendrl/monitoring_integration/grafana/dashboard.py
tendrl/monitoring_integration/grafana/dashboard_utils.py
tendrl/monitoring_integration/grafana/datasource_utils.py
tendrl/monitoring_integration/grafana/grafana_org_utils.py
tendrl/monitoring_integration/grafana/notification_channel.py
tendrl/monitoring_integration/grafana/utils.py
tendrl/monitoring_integration/graphite/__init__.py
tendrl/monitoring_integration/objects/config/__init__.py
tendrl/monitoring_integration/sync/__init__.py
tendrl/monitoring_integration/tests/objects/alert_organization/test_init.py
tendrl/monitoring_integration/upgrades/delete_dashboards.py

bugzilla: 1590416
tendrl-bug-id: Tendrl/monitoring-integration#577

Added subpath("/grafana") in grafana root_url for reverse proxy
